---
title: "featureColorStates"
author: "EC"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)   
library(ggplot2) 
library(lubridate)
library(caret)
```

```{r} 
#String Constants
trnsact_filename <- "trnsact10k.csv"
str_filename <- "strinfo_h.csv"
sku_filename <- "skuinfo10K.csv"
trnsact_sample_query <-"SELECT * FROM trnsact ORDER BY RANDOM() LIMIT 10000;"
sku_sample_query <- "SELECT * FROM skuinfo ORDER BY RANDOM() LIMIT 10000;"
str_query <- "SELECT storeid, state FROM strinfo;"

#Dictionary about colors
colors = c("red", "yellow", "green", "blue", "white", "black", "pink", "purple")

#State-Region Mapping


```

```{r}
#helper function

#A Mode for categorical variable, to give every sku a state it's most sold in
calculate_mode <- function(x) {
  uniqx <- unique(na.omit(x))
  uniqx[which.max(tabulate(match(x, uniqx)))]
}

```


```{r}
#load the data, merge the state to sku based on the most frequently bought state regions
#Doing this step here because the SQL query was taking too long, need to get feature engineering started with some data first. Later will do this in SQL.
str <- read.csv(str_filename,
                header = TRUE, sep = ",") %>% rename(store = storeid)
trnsact <- read.csv(trnsact_filename, 
                    header = TRUE, sep = ",") %>% select(sku, store) %>%
          left_join(str, by = "store") #use store table to get state of transactions
sku <- read.csv(sku_filename,
                header = TRUE, sep = ",") %>% 
  select(sku, color) %>%
  left_join(trnsact, by = "sku") %>% #use sku to join transaction+state and sku
  group_by(sku) %>%
  summarise(sku, color, state = calculate_mode(state)) %>% #for each sku which state did it sell best?
  filter(!is.na(state))
# because the limitation of the data sample, basically only 62 matches were found between the transact and sku. It won't be a problem when we actually apply this to a larger data set.
```




```{r}
#State and color are both categorical variables. Need to one-hot encode it.
dummy <- dummyVars(" ~ .", data=sku)
sku <- data.frame(predict(dummy, newdata=sku))

#We see there are way too many columns here. Need to group colors into buckets. Coral and Salmon are both pink. Will do that next time.
#Also without losing info granularity, we are considering grouping different states into regions - West, Southwest, Midwest, Southeast, Northeast, Etc.
```